kind: Deployment
apiVersion: apps/v1
metadata:
  name: itemapi
  labels:
    app: item
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item
  template:
    metadata:
      labels:
        app: item
    spec:
      containers:
        - name: msa-go-itemapi
          image: docker.io/dainforest/msa-go-itemapi:v1